# Generated by Django 5.1.4 on 2024-12-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="ID сессии"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="url",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка на сессию"
            ),
        ),
    ]
