# Generated by Django 5.1.4 on 2025-01-02 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_course_owner_lesson_owner"),
        ("users", "0005_payment_session_id_payment_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscribes",
                to="course.course",
                verbose_name="Подписанный курс",
            ),
        ),
    ]
