# Generated by Django 5.1.4 on 2025-01-02 13:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                max_length=30,
                null=True,
                verbose_name="Дата и время создание курса",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                max_length=30,
                null=True,
                verbose_name="Дата и время обновление курса",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                max_length=30,
                null=True,
                verbose_name="Дата и время создание урока",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                max_length=30,
                null=True,
                verbose_name="Дата и время обновление урока",
            ),
        ),
    ]
