# Generated by Django 5.1.4 on 2025-01-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_course_created_at_course_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                max_length=30,
                null=True,
                verbose_name="Дата и время создание урока",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                max_length=30,
                null=True,
                verbose_name="Дата и время обновление урока",
            ),
        ),
    ]
