# Generated by Django 5.1.4 on 2025-01-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_lesson_created_at_alter_lesson_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                max_length=30,
                null=True,
                verbose_name="Дата и время создание курса",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                max_length=30,
                null=True,
                verbose_name="Дата и время обновление курса",
            ),
        ),
    ]
